{{- if (include "terraform.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terraform.fullname" . }}
type: Opaque
data:
  credentials.json: {{ .Values.google.serviceAccountKey | b64enc | quote }}
{{- end}}
